import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'az-catalog-uchastnik-card',
  templateUrl: './catalog-uchastnik-card.component.html',
  styleUrls: ['./catalog-uchastnik-card.component.less'],
})
export class CatalogUchastnikCardComponent implements OnInit {
  array = [
    {
      logo: './assets/images/agrozamin/logo1.svg',
      title: 'Агротерра',
      name: 'Производство семян и саженцев',
      address: ' Ташкентская область, Ташкент',
      text: 'Вот вам яркий пример современных тенденций - сплочённость команды профессионалов позволяет выполнить важные ...',
      img1: './assets/images/agrozamin/image1.jpg',
      img2: './assets/images/agrozamin/image2.jpg',
      img3: './assets/images/agrozamin/image3.jpg',
      img4: './assets/images/agrozamin/image4.jpg',
    },
    {
      logo: './assets/images/agrozamin/logo2.svg',
      title: 'Сельхозпак',
      name: 'овощи оптом',
      address: ' Навоийская область, Нурата',
      text: 'Высокий уровень вовлечения представителей целевой аудитории является четким доказательством простого ...',
      img1: './assets/images/agrozamin/image5.jpg',
      img2: './assets/images/agrozamin/image6.jpg',
      img3: './assets/images/agrozamin/image7.jpg',
      img4: './assets/images/agrozamin/image8.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo2.svg',
      title: 'Рубеж',
      name: 'Разведение крупного рогатого скота',
      address: 'Хорезмская область, Хорезм',
      text: 'Предварительные выводы неутешительны: дальнейшее развитие различных форм деятельности создаёт ...',
      img1: './assets/images/agrozamin/image17.jpg',
      img2: './assets/images/agrozamin/image18.jpg',
      img3: './assets/images/agrozamin/image19.jpg',
      img4: './assets/images/agrozamin/image20.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo3.svg',
      title: 'Пеленг',
      name: 'Сельхозоборудование ',
      address: 'Ташкентская область, Ташкент',
      text: 'Предприниматели в сети интернет преданы социально-демократической анафеме.',
      img1: './assets/images/agrozamin/image9.jpg',
      img2: './assets/images/agrozamin/image10.jpg',
      img3: './assets/images/agrozamin/image11.jpg',
      img4: './assets/images/agrozamin/image12.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo4.svg',
      title: 'Рубеж',
      name: 'Овощи и фрукты',
      address: 'Самаркандская область, Каттакурган',
      text: 'В рамках спецификации современных стандартов, непосредственные участники технического прогресса ...',
      img1: './assets/images/agrozamin/image21.jpg',
      img2: './assets/images/agrozamin/image22.jpg',
      img3: './assets/images/agrozamin/image23.jpg',
      img4: './assets/images/agrozamin/image24.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo5.svg',
      title: 'Viola',
      name: 'Семена',
      address: 'Самаркандская область, Каттакурган',
      text: 'Значимость этих проблем настолько очевидна, что существующая теория в значительной степени ...',
      img1: './assets/images/agrozamin/image25.jpg',
      img2: './assets/images/agrozamin/image26.jpg',
      img3: './assets/images/agrozamin/image27.jpg',
      img4: './assets/images/agrozamin/image28.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo6.svg',
      title: 'Агростор',
      name: 'Уход и выращивание',
      address: 'Ташкентская область, Ташкент',
      text: 'Лишь тщательные исследования конкурентов могут быть объединены в целые кластеры себе подобных.',
      img1: './assets/images/agrozamin/image29.png',
      img2: './assets/images/agrozamin/image30.jpg',
      img3: './assets/images/agrozamin/image31.jpg',
      img4: './assets/images/agrozamin/image32.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo7.svg',
      title: 'Ариант',
      name: 'Спецтехника',
      address: 'Хорезмская область, Хорезм',
      text: 'Стремящиеся вытеснить традиционное производство, нанотехнологии, которые представляют собой яркий пример ...',
      img1: './assets/images/agrozamin/image33.jpg',
      img2: './assets/images/agrozamin/image34.jpg',
      img3: './assets/images/agrozamin/image35.jpg',
      img4: './assets/images/agrozamin/image36.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo8.svg',
      title: 'Syngenta',
      name: 'Спецтехника',
      address: 'Самаркандская область, Каттакурган',
      text: 'Явные признаки победы институционализации функционально разнесены на независимые элементы.',
      img1: './assets/images/agrozamin/image37.jpg',
      img2: './assets/images/agrozamin/image38.jpg',
      img3: './assets/images/agrozamin/image39.jpg',
      img4: './assets/images/agrozamin/image40.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo9.svg',
      title: 'TNK',
      name: 'Мелкий рогатый скот',
      address: 'Хорезмская область, Хорезм',
      text: 'Есть над чем задуматься: базовые сценарии поведения пользователей объединены в целые кластеры себе подобных.',
      img1: './assets/images/agrozamin/image41.jpg',
      img2: './assets/images/agrozamin/image42.jpg',
      img3: './assets/images/agrozamin/image43.jpg',
      img4: './assets/images/agrozamin/image44.jpg',
    },
    {
      logo: './assets/images/agrozamin/logo1.svg',
      title: 'Агротерра',
      name: 'Производство семян и саженцев',
      address: ' Ташкентская область, Ташкент',
      text: 'Вот вам яркий пример современных тенденций - сплочённость команды профессионалов позволяет выполнить важные ...',
      img1: './assets/images/agrozamin/image1.jpg',
      img2: './assets/images/agrozamin/image2.jpg',
      img3: './assets/images/agrozamin/image3.jpg',
      img4: './assets/images/agrozamin/image4.jpg',
    },
    {
      logo: './assets/images/agrozamin/logo2.svg',
      title: 'Сельхозпак',
      name: 'овощи оптом',
      address: ' Навоийская область, Нурата',
      text: 'Высокий уровень вовлечения представителей целевой аудитории является четким доказательством простого ...',
      img1: './assets/images/agrozamin/image5.jpg',
      img2: './assets/images/agrozamin/image6.jpg',
      img3: './assets/images/agrozamin/image7.jpg',
      img4: './assets/images/agrozamin/image8.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo2.svg',
      title: 'Рубеж',
      name: 'Разведение крупного рогатого скота',
      address: 'Хорезмская область, Хорезм',
      text: 'Предварительные выводы неутешительны: дальнейшее развитие различных форм деятельности создаёт ...',
      img1: './assets/images/agrozamin/image17.jpg',
      img2: './assets/images/agrozamin/image18.jpg',
      img3: './assets/images/agrozamin/image19.jpg',
      img4: './assets/images/agrozamin/image20.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo3.svg',
      title: 'Пеленг',
      name: 'Сельхозоборудование ',
      address: 'Ташкентская область, Ташкент',
      text: 'Предприниматели в сети интернет преданы социально-демократической анафеме.',
      img1: './assets/images/agrozamin/image9.jpg',
      img2: './assets/images/agrozamin/image10.jpg',
      img3: './assets/images/agrozamin/image11.jpg',
      img4: './assets/images/agrozamin/image12.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo4.svg',
      title: 'Рубеж',
      name: 'Овощи и фрукты',
      address: 'Самаркандская область, Каттакурган',
      text: 'В рамках спецификации современных стандартов, непосредственные участники технического прогресса ...',
      img1: './assets/images/agrozamin/image21.jpg',
      img2: './assets/images/agrozamin/image22.jpg',
      img3: './assets/images/agrozamin/image23.jpg',
      img4: './assets/images/agrozamin/image24.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo5.svg',
      title: 'Viola',
      name: 'Семена',
      address: 'Самаркандская область, Каттакурган',
      text: 'Значимость этих проблем настолько очевидна, что существующая теория в значительной степени ...',
      img1: './assets/images/agrozamin/image25.jpg',
      img2: './assets/images/agrozamin/image26.jpg',
      img3: './assets/images/agrozamin/image27.jpg',
      img4: './assets/images/agrozamin/image28.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo6.svg',
      title: 'Агростор',
      name: 'Уход и выращивание',
      address: 'Ташкентская область, Ташкент',
      text: 'Лишь тщательные исследования конкурентов могут быть объединены в целые кластеры себе подобных.',
      img1: './assets/images/agrozamin/image29.png',
      img2: './assets/images/agrozamin/image30.jpg',
      img3: './assets/images/agrozamin/image31.jpg',
      img4: './assets/images/agrozamin/image32.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo7.svg',
      title: 'Ариант',
      name: 'Спецтехника',
      address: 'Хорезмская область, Хорезм',
      text: 'Стремящиеся вытеснить традиционное производство, нанотехнологии, которые представляют собой яркий пример ...',
      img1: './assets/images/agrozamin/image33.jpg',
      img2: './assets/images/agrozamin/image34.jpg',
      img3: './assets/images/agrozamin/image35.jpg',
      img4: './assets/images/agrozamin/image36.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo8.svg',
      title: 'Syngenta',
      name: 'Спецтехника',
      address: 'Самаркандская область, Каттакурган',
      text: 'Явные признаки победы институционализации функционально разнесены на независимые элементы.',
      img1: './assets/images/agrozamin/image37.jpg',
      img2: './assets/images/agrozamin/image38.jpg',
      img3: './assets/images/agrozamin/image39.jpg',
      img4: './assets/images/agrozamin/image40.jpg',
    },
    {
      logo: './assets/images/agrozamin/uchastnikLOgo9.svg',
      title: 'TNK',
      name: 'Мелкий рогатый скот',
      address: 'Хорезмская область, Хорезм',
      text: 'Есть над чем задуматься: базовые сценарии поведения пользователей объединены в целые кластеры себе подобных.',
      img1: './assets/images/agrozamin/image41.jpg',
      img2: './assets/images/agrozamin/image42.jpg',
      img3: './assets/images/agrozamin/image43.jpg',
      img4: './assets/images/agrozamin/image44.jpg',
    },
  ];

  constructor() {}

  ngOnInit(): void {}
}
